FROM adoptopenjdk:11-jdk-hotspot AS builder
WORKDIR /build
COPY mvnw .
COPY .mvn/wrapper .mvn/wrapper
COPY pom.xml .
# This is for windows to replace windows end of line by linux end of line
RUN apt-get update && apt-get install -y dos2unix
RUN dos2unix mvnw
RUN ./mvnw dependency:go-offline
COPY src/ src
# This is for windows to replace windows end of line by linux end of line
RUN ./mvnw spring-javaformat:apply
RUN ./mvnw package -DskipTests

FROM gcr.io/distroless/java
WORKDIR /app
COPY --from=builder /build/target/spring-petclinic-*jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
